/**
 * ESLint 9 flat config.
 *
 * WHY THIS EXISTS: eslint 9.23 and its React plugins were already installed,
 * but with no `eslint.config.js` the CLI had nothing to read, so `npx eslint .`
 * could not run at all. Linting only happened inside craco's dev overlay, which
 * means it only ever saw the files a dev server happened to compile and could
 * not be run over the whole tree or in CI.
 *
 * SEVERITY POLICY, DELIBERATE: everything here is a WARNING, and this config is
 * NOT wired into `npm run build`. The build gate is `CI=true craco build`,
 * which treats its own warnings as errors; turning a pre-existing lint backlog
 * into build failures would have blocked the bundle-splitting work this config
 * shipped alongside. Fix the backlog first, then promote the clean rules.
 *
 * ORDERING MATTERS: flat config merges `languageOptions` shallowly and later
 * entries win, so `parserOptions` set by a preset REPLACES an earlier one
 * wholesale. The presets therefore come first and the shared
 * language/rule block comes last - with the reverse order the presets reset
 * `ecmaVersion` and every `?.` and `??` in the codebase reported as a parse
 * error.
 */
const js = require('@eslint/js');
const globals = require('globals');
const react = require('eslint-plugin-react');
const reactHooks = require('eslint-plugin-react-hooks');
const jsxA11y = require('eslint-plugin-jsx-a11y');
const importPlugin = require('eslint-plugin-import');

const FILES = ['**/*.{js,jsx}'];

/** Warn instead of error for every rule a preset turns on. */
const downgradeToWarn = (config) => ({
    ...config,
    files: FILES,
    rules: Object.fromEntries(
        Object.entries(config.rules || {}).map(([name, level]) => {
            const options = Array.isArray(level) ? level.slice(1) : [];
            return [name, options.length > 0 ? ['warn', ...options] : 'warn'];
        })
    ),
});

module.exports = [
    {
        // `build/` is compiled output and `src/components/ui/` is generated by
        // the shadcn CLI - both are rewritten wholesale, so findings in them
        // are noise no one can act on without losing the generator.
        // `src/hooks/use-toast.js` is the same shadcn output (installed with
        // ui/toast); its unused `actionTypes` is a type-only value in the
        // TypeScript original.
        ignores: [
            'build/**',
            'node_modules/**',
            'coverage/**',
            '.netlify/**',
            'src/components/ui/**',
            'src/hooks/use-toast.js',
        ],
    },

    downgradeToWarn(js.configs.recommended),
    downgradeToWarn(react.configs.flat.recommended),
    downgradeToWarn(jsxA11y.flatConfigs.recommended),
    downgradeToWarn(importPlugin.flatConfigs.recommended),

    {
        files: FILES,
        plugins: { 'react-hooks': reactHooks },
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                ...globals.browser,
                ...globals.es2022,
                ...globals.node,
            },
            parserOptions: {
                ecmaVersion: 2022,
                sourceType: 'module',
                ecmaFeatures: { jsx: true },
            },
        },
        settings: {
            // React 19. Without this the plugin assumes the oldest supported
            // version for every version-dependent rule.
            react: { version: 'detect' },
            'import/resolver': {
                node: { extensions: ['.js', '.jsx'] },
            },
        },
        rules: {
            // The two hook rules that catch real bugs rather than style: a hook
            // called conditionally, and a stale closure from a missing dep.
            'react-hooks/rules-of-hooks': 'warn',
            'react-hooks/exhaustive-deps': 'warn',

            // Automatic JSX runtime (CRA 5 / React 19): `import React` is not
            // required. Kept ON rather than off so that the explicit
            // `import React` these files do carry counts as a use and does not
            // trip no-unused-vars on ~20 files.
            'react/react-in-jsx-scope': 'off',
            'react/jsx-uses-react': 'warn',
            // Props are documented with JSDoc; prop-types is not used here.
            'react/prop-types': 'off',

            // `@/` is resolved by craco/jsconfig, not by the node resolver, so
            // the import plugin cannot follow it.
            'import/no-unresolved': 'off',
            'import/named': 'off',
            // These three re-parse every imported module with the import
            // plugin's own default parser, which does not know JSX or optional
            // chaining - so they report "Parse errors in imported module" for
            // ordinary application files rather than anything actionable.
            'import/namespace': 'off',
            'import/default': 'off',
            'import/export': 'off',

            'no-unused-vars': ['warn', {
                argsIgnorePattern: '^_',
                varsIgnorePattern: '^_',
                caughtErrors: 'none',
                // `const { dropped, ...rest } = obj` is the idiomatic way to
                // omit keys immutably; `dropped` is intentionally unused.
                ignoreRestSiblings: true,
            }],
            'no-console': ['warn', { allow: ['warn', 'error'] }],
        },
    },

    {
        // Tests and setup run under jest.
        files: ['**/*.test.{js,jsx}', 'src/setupTests.js', 'src/lib/__mocks__/**'],
        languageOptions: {
            globals: { ...globals.jest, ...globals.node },
        },
    },

    {
        // Build tooling is CommonJS and runs in node.
        files: ['craco.config.js', 'postcss.config.js', 'tailwind.config.js', 'eslint.config.js'],
        languageOptions: {
            sourceType: 'commonjs',
            globals: { ...globals.node },
        },
    },
];
