services:
  - type: web
    name: timestin-crm-backend-backup
    runtime: node
    region: singapore
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CRON_SECRET
        sync: false
      - key: CORS_ORIGINS
        value: https://timestin-crm.netlify.app
      - key: NODE_ENV
        value: production
